# Generated by Django 5.0.6 on 2024-06-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_drivers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("username",)},
        ),
    ]
