# Generated by Django 5.0.6 on 2024-06-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ("name",)},
        ),
    ]
